### ISSUE TITLE
Unable to send transaction(s) to tor - no available outbound connections

### ISSUE THREAD

**Issue by urza-lab** [sethforprivacy/simple-monerod-docker#154]
Transaction initiated via Exodus Mobile Wallet connected to fully synced Monero Node reverse proxied via Caddy (separate container) hosted within Debian LXC on Proxmox using docker is not sent to the Blockchain. What did I miss?

docker logs monerod
`2025-02-13 22:06:04.323 W Unable to send transaction(s) to tor - no available outbound connections`

monerod status executed within container
`2025-02-13 23:24:44.054 I Monero 'Fluorine Fermi' (v0.18.3.4-release)
Height: 3347069/3347069 (100.0%) on mainnet, not mining, net hash 4.22 GH/s, v16, 63(out)+0(in) connections, uptime 0d 0h 33m 50s`

docker-compose.yml in line with monerosuite
```
name: monero-suite
services:
  monerod:
    image: ghcr.io/sethforprivacy/simple-monerod:latest
    restart: unless-stopped
    container_name: monerod
    volumes:
      - bitmonero:/home/monero/.bitmonero
    ports:
      - 18080:18080
      - 18089:18089
    depends_on:
      tor-proxy:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:18081/get_height || exit 1
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 40s
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=18081
      - --confirm-external-bind
      - --enable-dns-blocklist
      - --check-updates=disabled
      - --max-log-files=3
      - --max-log-file-size=1048576
      - --no-igd
      - --out-peers=64
      - --limit-rate-down=1048576
      - --prune-blockchain
      - --public-node
      - --no-zmq
      - --tx-proxy=tor,127.0.0.1:9150,32
      - --add-priority-node=xwvz3ekocr3dkyxfkmgm2hvbpzx2ysqmaxgter7znnqrhoicygkfswid.onion:18083
      - --add-priority-node=4pixvbejrvihnkxmduo2agsnmc3rrulrqc7s3cbwwrep6h6hrzsibeqd.onion:18083
      - --add-priority-node=zbjkbsxc5munw3qusl7j2hpcmikhqocdf4pqhnhtpzw5nt5jrmofptid.onion:18083
      - --add-priority-node=plowsof3t5hogddwabaeiyrno25efmzfxyro2vligremt7sxpsclfaid.onion:18083
      - --add-priority-node=plowsoffjexmxalw73tkjmf422gq6575fc7vicuu4javzn2ynnte6tyd.onion:18083
      - --add-priority-node=qz43zul2x56jexzoqgkx2trzwcfnr6l3hbtfcfx54g4r3eahy3bssjyd.onion:18083
      - --add-peer=xwvz3ekocr3dkyxfkmgm2hvbpzx2ysqmaxgter7znnqrhoicygkfswid.onion:18083
      - --add-peer=4pixvbejrvihnkxmduo2agsnmc3rrulrqc7s3cbwwrep6h6hrzsibeqd.onion:18083
      - --add-peer=zbjkbsxc5munw3qusl7j2hpcmikhqocdf4pqhnhtpzw5nt5jrmofptid.onion:18083
      - --add-peer=plowsof3t5hogddwabaeiyrno25efmzfxyro2vligremt7sxpsclfaid.onion:18083
      - --add-peer=plowsoffjexmxalw73tkjmf422gq6575fc7vicuu4javzn2ynnte6tyd.onion:18083
      - --add-peer=qz43zul2x56jexzoqgkx2trzwcfnr6l3hbtfcfx54g4r3eahy3bssjyd.onion:18083
  moneroblock:
    image: sethsimmons/moneroblock:latest
    restart: unless-stopped
    container_name: moneroblock
    ports:
      - 31312:31312
    command:
      - --daemon
      - monerod:18089
  tor-proxy:
    image: ghcr.io/peterdavehello/tor-socks-proxy:latest
    container_name: tor-proxy
    restart: unless-stopped
    ports:
      - 9150:9150
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  bitmonero: {}
```
