### ISSUE TITLE
Local clients (miners) lose contact to monerod after a day or so

### ISSUE THREAD

**Issue by AntlerDM** [sethforprivacy/simple-monerod-docker#161]
I recently switched from systemd to docker for my monero node. Docker is new to me so,  I followed these instructions (https://sethforprivacy.com/guides/run-a-monero-node).

The install appears to be working, but after a day or two, local connections (xmrig miners) start getting intermittent "read error: "connection reset by peer"" messages. Then after a few more hours, the miner disconnects completely with a "no active pools, stop mining" message.

The miners do not go down at the same time. I frequently see 1 or 2 miners still working but others are not.

When some or all of the miners are disconnected, I can go into the shell of the monerod container and the status shows everything is fine. 

```
monerod status 
2025-03-20 22:14:16.599	I Monero 'Fluorine Fermi' (v0.18.3.4-release)
Height: 3372193/3372193 (100.0%) on mainnet, not mining, net hash 4.31 GH/s, v16, 12(out)+191(in) connections, uptime 4d 5h 17m 17s

```
The machine running docker has an entry in UFW for local clients (limited to local clients) on the port they are configured to use (18089). Although, I am unsure if ufw is even involved with the connections.

```
ufw status
18089/tcp                  ALLOW IN    192.168.10.0/24

```
I am using the following configuration...

```
services:
    monerod:
        image: ghcr.io/sethforprivacy/simple-monerod:latest
        restart: unless-stopped
        container_name: monerod
        volumes:
            - bitmonero:/home/monero/.bitmonero
        ports:
            - 18080:18080
            - 18089:18089
        command:
            - "--p2p-bind-ip=0.0.0.0"
            - "--rpc-restricted-bind-ip=0.0.0.0"
            - "--rpc-restricted-bind-port=18089"
            - "--public-node"
            - "--no-igd"
            - "--no-zmq"
            - "--enable-dns-blocklist"      tor:
        image: goldy/tor-hidden-service:latest
        container_name: tor
        restart: unless-stopped
        links:
            - monerod
        environment:
            MONEROD_TOR_SERVICE_HOSTS: 18089:monerod:18089
            MONEROD_TOR_SERVICE_VERSION: '3'
        volumes:
            - tor-keys:/var/lib/tor/hidden_service/
  volumes:
    bitmonero:
    tor-keys: 

```
The machine is running Ubuntu Server 24.10. A watchtower container is also running. I am also running a container for a BitTorrent client with a VPN that has stable (local and vpn) connections.
