### ISSUE TITLE
Failed to initialize core RPC server.

### ISSUE THREAD

**Issue by SturmB** [sethforprivacy/simple-monerod-docker#32]
I am getting that error message when attempting to run the docker image based on this docker-compose file on my Synology server:

```yml
---
version: '3.8'

volumes:
  bitmonero:
    driver: local

services:
  monero:
    image: sethsimmons/simple-monerod:latest
    container_name: monerod
    ports:
      - "18080:18080"
      - "18089:18089"
    volumes:
      - bitmonero:/home/monero
    restart: unless-stopped
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=18089 --no-igd --no-zmq --enable-dns-blocklist"
```

The full message in the logs is:
`2022-03-12 03:23:11.370	E Exception in main! Failed to initialize core RPC server.`

Do I have something set up wrong?

**Comment by SturmB** [comment]
Never mind. I had the `command` section wrong. Each argument should be its own item in the command list, like so:

```yml
---
version: '3.8'

volumes:
  bitmonero:
    driver: local

services:
  monero:
    image: sethsimmons/simple-monerod:latest
    container_name: monerod
    ports:
      - "18080:18080"
      - "18089:18089"
    volumes:
      - bitmonero:/home/monero
    restart: unless-stopped
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-port=18089"
      - "--no-igd"
      - "--no-zmq"
      - "--enable-dns-blocklist"
```

Now it appears to work and is currently syncing.

Although, I do wonder if I should be opening 18080 and 18089 on my router if I only ever intend to use this node locally and not from outside my network.
